"use client";

import { useEffect, useMemo, useState } from "react";
import { ChevronDown, Circle, ImagePlus, Search, Square, Star, Type, Upload, X } from "lucide-react";
import { DynamicIcon } from "lucide-react/dynamic";
import { LUCIDE_ICON_NAMES, humanizeLucideIconName, searchLucideIconNames, type LucideIconName } from "../domain/lucide-icon-catalog";
import type { MenuAssetView } from "../contracts";

type Section = "canvas" | "add" | "images" | "icons" | "fonts";
type Shape = "rect" | "ellipse" | "line" | "arrow" | "triangle" | "star";

export function EditorToolsPanel({ background, images, layersOpen, onToggleLayers, onOpenIcons, onBackgroundChange, onAddText, onAddShape, onAddImage, onUpload }: { background: string; images: MenuAssetView[]; layersOpen: boolean; onToggleLayers: () => void; onOpenIcons: (open: boolean) => void; onBackgroundChange: (value: string) => void; onAddText: () => void; onAddShape: (shape: Shape) => void; onAddImage: (asset: MenuAssetView) => void; onUpload: (kind: "IMAGE" | "FONT", file: File) => Promise<void> }) {
  const [open, setOpen] = useState<Section>("add");
  return <>
    <aside className="w-56 shrink-0 overflow-y-auto border-r border-zinc-200 bg-white p-3"><button type="button" className="mb-2 flex w-full items-center justify-between rounded-lg border border-zinc-200 px-2.5 py-2 text-left text-xs font-semibold text-zinc-700" onClick={onToggleLayers} aria-expanded={layersOpen}><span>Capas</span><span className="text-[11px] font-normal text-zinc-400">{layersOpen ? "Ocultar" : "Mostrar"}</span></button>
      <ToolSection id="canvas" label="Lienzo" open={open === "canvas"} onToggle={() => { onOpenIcons(false); setOpen(open === "canvas" ? "add" : "canvas"); }}><label className="flex items-center justify-between rounded-lg bg-zinc-50 px-2 py-2 text-xs font-medium">Color de fondo<input className="h-7 w-10 rounded border border-zinc-200" type="color" value={background} onChange={(event) => onBackgroundChange(event.target.value)} /></label></ToolSection>
      <ToolSection id="add" label="Agregar" open={open === "add"} onToggle={() => { onOpenIcons(false); setOpen(open === "add" ? "canvas" : "add"); }}><div className="grid grid-cols-2 gap-2"><ToolButton icon={<Type size={16} />} label="Texto" onClick={onAddText} /><ToolButton icon={<Square size={16} />} label="Rectángulo" onClick={() => onAddShape("rect")} /><ToolButton icon={<Circle size={16} />} label="Elipse" onClick={() => onAddShape("ellipse")} /><ToolButton icon={<Square size={16} />} label="Línea" onClick={() => onAddShape("line")} /><ToolButton icon={<Square size={16} />} label="Flecha" onClick={() => onAddShape("arrow")} /><ToolButton icon={<Star size={16} />} label="Estrella" onClick={() => onAddShape("star")} /><ToolButton icon={<Star size={16} />} label="Triángulo" onClick={() => onAddShape("triangle")} /></div></ToolSection>
      <ToolSection id="images" label="Imágenes" open={open === "images"} onToggle={() => { onOpenIcons(false); setOpen(open === "images" ? "add" : "images"); }}><div className="space-y-2">{images.map((asset) => <button key={asset.id} className="flex w-full items-center gap-2 rounded-lg border border-zinc-200 p-2 text-left text-xs hover:border-emerald-400" onClick={() => onAddImage(asset)}><ImagePlus size={15} /><span className="truncate">{asset.name}</span></button>)}<UploadButton label="Subir imagen" accept="image/jpeg,image/png,image/webp" onUpload={(file) => onUpload("IMAGE", file)} /></div></ToolSection>
      <ToolSection id="icons" label="Iconos" open={open === "icons"} onToggle={() => { setOpen("icons"); onOpenIcons(true); }}><button className="flex w-full items-center justify-center gap-2 rounded-lg border border-emerald-200 bg-emerald-50 px-3 py-2 text-xs font-medium text-emerald-800" onClick={() => onOpenIcons(true)}><Search size={14} /> Abrir biblioteca</button></ToolSection>
      <ToolSection id="fonts" label="Fuentes" open={open === "fonts"} onToggle={() => { onOpenIcons(false); setOpen(open === "fonts" ? "add" : "fonts"); }}><UploadButton label="Subir fuente" accept=".woff,.woff2,.ttf,.otf,font/woff,font/woff2,font/ttf,font/otf" onUpload={(file) => onUpload("FONT", file)} /></ToolSection>
    </aside>
  </>;
}

function ToolSection({ label, open, onToggle, children }: { id: Section; label: string; open: boolean; onToggle: () => void; children: React.ReactNode }) { return <section className="border-b border-zinc-100 py-1"><button type="button" className="flex w-full items-center justify-between px-1 py-2 text-left text-xs font-semibold text-zinc-700" onClick={onToggle} aria-expanded={open}>{label}<ChevronDown size={15} className={`transition-transform ${open ? "rotate-180" : ""}`} /></button>{open && <div className="pb-3 pt-1">{children}</div>}</section>; }
function ToolButton({ icon, label, onClick }: { icon: React.ReactNode; label: string; onClick: () => void }) { return <button onClick={onClick} className="flex flex-col items-center gap-1 rounded-lg border border-zinc-200 px-2 py-3 text-[11px] hover:border-emerald-400 hover:bg-emerald-50">{icon}<span>{label}</span></button>; }
function UploadButton({ label, accept, onUpload }: { label: string; accept: string; onUpload: (file: File) => void }) { return <label className="flex cursor-pointer items-center justify-center gap-2 rounded-lg border border-dashed border-zinc-300 px-3 py-2 text-xs font-medium text-zinc-600 hover:border-emerald-500"><Upload size={14} /> {label}<input className="hidden" type="file" accept={accept} onChange={(event) => { const file = event.target.files?.[0]; if (file) onUpload(file); event.currentTarget.value = ""; }} /></label>; }

export function IconPickerDrawer({ onClose, onSelect }: { onClose: () => void; onSelect: (name: string) => void }) {
  const [query, setQuery] = useState(""); const [limit, setLimit] = useState(72);
  useEffect(() => { const handler = (event: KeyboardEvent) => { if (event.key === "Escape") onClose(); }; window.addEventListener("keydown", handler); return () => window.removeEventListener("keydown", handler); }, [onClose]);
  const names = useMemo(() => searchLucideIconNames(query).slice(0, limit), [query, limit]);
  return <aside id="editor-icons" className="w-64 shrink-0 overflow-y-auto border-r border-zinc-200 bg-white p-3"><div className="mb-2 flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-widest text-zinc-400">Iconos</p><p className="mt-1 text-[10px] text-zinc-400">{LUCIDE_ICON_NAMES.length} diseños</p></div><button className="rounded p-1 text-zinc-500 hover:bg-zinc-100" onClick={onClose} aria-label="Volver a capas"><X size={17} /></button></div><label className="mb-3 flex items-center gap-2 rounded-lg border border-zinc-200 px-2 py-2"><Search size={15} className="text-zinc-400" /><input autoFocus className="min-w-0 flex-1 text-xs outline-none" placeholder="Buscar iconos..." value={query} onChange={(event) => { setQuery(event.target.value); setLimit(72); }} /></label><div className="grid grid-cols-3 gap-2">{names.map((name) => <button key={name} className="flex min-h-20 flex-col items-center justify-center gap-1 rounded-lg border border-zinc-100 p-2 text-center text-[10px] text-zinc-600 hover:border-emerald-400 hover:bg-emerald-50" onClick={() => onSelect(name)} aria-label={`Agregar icono ${humanizeLucideIconName(name)}`}><DynamicIcon name={name as LucideIconName} size={23} strokeWidth={1.8} /><span className="line-clamp-2">{humanizeLucideIconName(name)}</span></button>)}{limit < LUCIDE_ICON_NAMES.length && <button className="col-span-3 rounded-lg border border-zinc-200 py-2 text-xs" onClick={() => setLimit((value) => value + 72)}>Cargar más</button>}</div></aside>;
}
