"use client";

import { useState } from "react";
import type { MenuAssetView } from "../contracts";

export function FontLibraryClient({ initialAssets }: { initialAssets: MenuAssetView[] }) {
  const [assets, setAssets] = useState(initialAssets);
  const [message, setMessage] = useState("");
  return <div className="space-y-5"><form className="flex flex-wrap items-end gap-3" onSubmit={async (event) => { event.preventDefault(); const form = new FormData(event.currentTarget); const file = form.get("file"); if (!(file instanceof File)) return; form.set("kind", "FONT"); setMessage("Subiendo..."); const response = await fetch("/api/editor/assets", { method: "POST", body: form }); const payload = await response.json(); if (response.ok && payload.success) { setAssets((items) => [payload.data, ...items]); setMessage("Fuente agregada"); event.currentTarget.reset(); } else setMessage(payload.error?.message ?? "No se pudo subir"); }}><label className="flex-1 text-sm font-medium">Nombre<input name="name" className="mt-1 w-full rounded-lg border border-zinc-200 px-3 py-2" placeholder="Fuente de marca" required /></label><label className="text-sm font-medium">Archivo<input name="file" className="mt-1 block text-sm" type="file" accept=".woff,.woff2,.ttf,.otf" required /></label><button className="rounded-lg bg-emerald-950 px-4 py-2 text-sm font-semibold text-white" type="submit">Subir fuente</button></form><p className="text-xs text-zinc-500">{message || "Formatos admitidos: WOFF, WOFF2, TTF y OTF. La fuente se elige en el inspector del editor."}</p><div className="divide-y rounded-xl border border-zinc-200">{assets.map((asset) => <div key={asset.id} className="flex items-center justify-between gap-3 px-4 py-3"><div><p className="text-sm font-semibold">{asset.name}</p><p className="text-xs text-zinc-500">{asset.mimeType} · {Math.ceil(asset.byteSize / 1024)} KB</p></div><button className="text-xs text-red-700" onClick={async () => { const response = await fetch(`/api/editor/assets/${asset.id}`, { method: "DELETE" }); if (response.ok) setAssets((items) => items.filter((item) => item.id !== asset.id)); else setMessage("No se puede eliminar una fuente en uso"); }}>Eliminar</button></div>)}</div></div>;
}
