"use client";

import { useState } from "react";
import { SYSTEM_FONT_FAMILIES, type MenuAssetView } from "../contracts";

export function FontLibraryClient({ initialAssets }: { initialAssets: MenuAssetView[] }) {
  const [assets, setAssets] = useState(initialAssets);
  const [message, setMessage] = useState("");
  const fontFaces = assets.map((asset) => `@font-face{font-family:"editor-font-${asset.id}";src:url("${asset.url}");font-display:swap;}`).join("");
  return <div className="space-y-6"><style dangerouslySetInnerHTML={{ __html: fontFaces }} /><div><p className="mb-3 text-xs font-bold uppercase tracking-widest text-zinc-400">Fuentes disponibles sin subir</p><div className="grid gap-2 sm:grid-cols-2">{SYSTEM_FONT_FAMILIES.map((family) => <div key={family} className="rounded-lg border border-zinc-200 px-3 py-2" style={{ fontFamily: family }}><p className="text-base">{family}</p><p className="text-[11px] text-zinc-500" style={{ fontFamily: "Arial" }}>Se elige desde el inspector del texto</p></div>)}</div></div><form className="flex flex-wrap items-end gap-3 border-t border-zinc-100 pt-5" onSubmit={async (event) => { event.preventDefault(); const form = new FormData(event.currentTarget); const file = form.get("file"); if (!(file instanceof File)) return; form.set("kind", "FONT"); setMessage("Subiendo..."); const response = await fetch("/api/editor/assets", { method: "POST", body: form }); const payload = await response.json(); if (response.ok && payload.success) { setAssets((items) => [payload.data, ...items]); setMessage("Fuente agregada"); event.currentTarget.reset(); } else setMessage(payload.error?.message ?? "No se pudo subir"); }}><label className="flex-1 text-sm font-medium">Nombre<input name="name" className="mt-1 w-full rounded-lg border border-zinc-200 px-3 py-2" placeholder="Fuente de marca" required /></label><label className="text-sm font-medium">Archivo<input name="file" className="mt-1 block text-sm" type="file" accept=".woff,.woff2,.ttf,.otf" required /></label><button className="rounded-lg bg-emerald-950 px-4 py-2 text-sm font-semibold text-white" type="submit">Subir fuente</button></form><p className="text-xs text-zinc-500">{message || "Formatos admitidos: WOFF, WOFF2, TTF y OTF. Máximo 10 MB por fuente y dentro de la cuota del restaurante."}</p><div className="divide-y rounded-xl border border-zinc-200">{assets.map((asset) => <div key={asset.id} className="flex items-center justify-between gap-3 px-4 py-3"><div style={{ fontFamily: `editor-font-${asset.id}` }}><p className="text-sm font-semibold">{asset.name}</p><p className="text-xs text-zinc-500" style={{ fontFamily: "Arial" }}>{asset.mimeType} · {Math.ceil(asset.byteSize / 1024)} KB</p></div><button type="button" className="text-xs text-red-700" onClick={async () => { const response = await fetch(`/api/editor/assets/${asset.id}`, { method: "DELETE" }); if (response.ok) setAssets((items) => items.filter((item) => item.id !== asset.id)); else setMessage("No se puede eliminar una fuente en uso"); }}>Eliminar</button></div>)}</div></div>;
}
