import { STROKE_SIDES, type CanvasDocumentV1, type CanvasNode, type MenuTemplateView } from "../contracts";
import { allCornerRadii } from "./rectangle-border";

const base = (id: string, x: number, y: number, width: number, height: number): Pick<CanvasNode, "id" | "x" | "y" | "width" | "height" | "rotation" | "opacity" | "visible" | "locked" | "groupId" | "link"> => ({ id, x, y, width, height, rotation: 0, opacity: 1, visible: true, locked: false, groupId: null, link: null });
function text(id: string, value: string, frame: [number, number, number, number], style: Partial<Extract<CanvasNode, { type: "text" }>> = {}): CanvasNode { return { ...base(id, ...frame), type: "text", text: value, modalAssetId: null, fontAssetId: null, fontFamily: "Arial", fontSize: 34, fontWeight: "400", fontStyle: "normal", textDecoration: "none", align: "left", verticalAlign: "middle", lineHeight: 1.2, letterSpacing: 0, fill: "#171717", semanticRole: "paragraph", ...style }; }
function shape(id: string, kind: Extract<CanvasNode, { type: "shape" }>['shape'], frame: [number, number, number, number], fill: string, stroke: string | null = null): CanvasNode { return { ...base(id, ...frame), type: "shape", shape: kind, fill, stroke, strokeWidth: stroke ? 2 : 0, strokeSides: [...STROKE_SIDES], cornerRadii: allCornerRadii(kind === "rect" ? 22 : 0) }; }
function icon(id: string, iconKey: string, frame: [number, number, number, number], fill: string): CanvasNode { return { ...base(id, ...frame), type: "icon", iconKey, accessibleLabel: iconKey, fill, strokeWidth: 2 }; }
function doc(bounds: CanvasDocumentV1["canvasBounds"], background: string, nodes: CanvasNode[]): CanvasDocumentV1 { return { schemaVersion: 1, background, canvasBounds: bounds, initialViewport: bounds, nodes, groups: [] }; }

export const TEMPLATE_PRESETS: ReadonlyArray<{ id: string; name: string; description: string; document: CanvasDocumentV1 }> = [
  { id: "preset-minimalista", name: "Minimalista vertical", description: "Una carta clara, ordenada y fácil de leer.", document: doc({ x: 0, y: 0, width: 1080, height: 1600 }, "#FAFAF8", [text("minimal-title", "Tu restaurante", [80, 90, 920, 110], { fontFamily: "Georgia", fontSize: 76, fontWeight: "800", fill: "#171717", semanticRole: "heading" }), text("minimal-subtitle", "Menú del día", [84, 215, 900, 50], { fontSize: 30, fill: "#666666" }), shape("minimal-line", "line", [84, 300, 900, 4], "#171717"), text("minimal-section", "Entradas", [84, 370, 900, 62], { fontSize: 42, fontWeight: "700", semanticRole: "heading" }), text("minimal-copy", "Agregá tus platos, ingredientes y precios desde el editor.", [84, 450, 850, 100], { fontSize: 28, fill: "#555555" }), shape("minimal-card", "rect", [84, 620, 900, 230], "#FFFFFF", "#E5E5E0"), text("minimal-card-title", "Plato destacado", [120, 670, 560, 52], { fontSize: 34, fontWeight: "700", semanticRole: "label" }), text("minimal-card-price", "$ 0,00", [760, 670, 170, 52], { fontSize: 32, fontWeight: "700", align: "right", semanticRole: "price" }), text("minimal-card-copy", "Descripción breve del plato.", [120, 740, 700, 44], { fontSize: 24, fill: "#666666" })]) },
  { id: "preset-cafeteria", name: "Cafetería", description: "Un estilo cálido para desayunos, café y pastelería.", document: doc({ x: 0, y: 0, width: 1600, height: 1000 }, "#F3E4CF", [icon("cafe-icon", "coffee", [100, 90, 90, 90], "#8A4B2A"), text("cafe-title", "Café & encuentros", [220, 90, 1100, 100], { fontFamily: "Georgia", fontSize: 72, fontWeight: "800", fill: "#6B351F", semanticRole: "heading" }), text("cafe-subtitle", "Desayunos · Meriendas · Pastelería", [225, 205, 900, 44], { fontSize: 28, fill: "#8A4B2A" }), shape("cafe-divider", "line", [100, 300, 1400, 4], "#B8790A"), text("cafe-section", "Bebidas calientes", [100, 370, 700, 64], { fontSize: 44, fontWeight: "700", fill: "#6B351F", semanticRole: "heading" }), text("cafe-item", "Café de especialidad", [125, 480, 800, 48], { fontSize: 32, fontWeight: "600", semanticRole: "label" }), text("cafe-price", "$ 0,00", [1200, 480, 250, 48], { fontSize: 32, fontWeight: "700", align: "right", fill: "#6B351F", semanticRole: "price" }), shape("cafe-card", "rect", [100, 620, 1400, 220], "#FFF8EF", "#D7B48C"), icon("cafe-card-icon", "cup-soda", [130, 680, 70, 70], "#B8790A"), text("cafe-card-copy", "Sumá una descripción deliciosa para cada producto.", [240, 690, 1100, 60], { fontSize: 30, fill: "#6B351F" })]) },
  { id: "preset-gourmet", name: "Gourmet", description: "Una composición elegante con contraste y acentos dorados.", document: doc({ x: 0, y: 0, width: 1400, height: 1400 }, "#1F2421", [icon("gourmet-spark", "sparkles", [630, 90, 140, 140], "#D9B36C"), text("gourmet-title", "La mesa", [120, 285, 1160, 120], { fontFamily: "Georgia", fontSize: 92, fontWeight: "800", align: "center", fill: "#F8EFD9", semanticRole: "heading" }), text("gourmet-subtitle", "Cocina de autor", [180, 430, 1040, 54], { fontSize: 30, align: "center", fill: "#D9B36C" }), shape("gourmet-line", "line", [260, 560, 880, 4], "#D9B36C"), text("gourmet-section", "Menú degustación", [180, 660, 1040, 70], { fontSize: 46, fontWeight: "700", align: "center", fill: "#F8EFD9", semanticRole: "heading" }), text("gourmet-copy", "Diseñá una experiencia memorable con tus platos y vinos.", [220, 770, 960, 100], { fontSize: 30, align: "center", fill: "#D8D2C4" }), icon("gourmet-star", "star", [640, 980, 120, 120], "#D9B36C")]) },
];

export function presetAsView(preset: typeof TEMPLATE_PRESETS[number]): MenuTemplateView { const now = new Date(0).toISOString(); return { id: preset.id, name: preset.name, description: preset.description, visibility: "PUBLIC", status: "PUBLISHED", isSystem: true, tenantId: null, document: preset.document, rejectionReason: null, createdAt: now, updatedAt: now }; }
